### ISSUE TITLE
Diffusers 0.26.3

### ISSUE THREAD

**Issue by elismasilva** [horseee/DeepCache#25]
Hi you need update pipeline XL to work with last version of Diffusers...

**Comment by horseee** [comment]
Hi @elismasilva,

I tested DeepCache under diffusers==0.26.3 and it works well. Can you give me the code snippet that can reproduce the bug/error?

**Comment by elismasilva** [comment]
#23 Looking now at the history I suppose this is related, this pipeline is for 0.24 diffusers right?

**Comment by horseee** [comment]
> #23 Looking now at the history I suppose this is related, this pipeline is for 0.24 diffusers right?
Yes. If you want to use the code in DeepCache.sdxl.pipeline_stable_diffusion_xl, than Diffusers needs to be downgraded to 0.24(test passed under 0.21.3<diffusers<0.25.0). 

And another way is to install the package `DeepCache` and follow the [instruction](https://github.com/horseee/DeepCache?tab=readme-ov-file#usage) to run the pipeline (or use DeepCache.extension.deepcache, the same). This implementation can support the latest versions of diffusers so far.
