### ISSUE TITLE
Details of the reproduction of the experimental results

### ISSUE THREAD

**Issue by ZTzxj** [horseee/DeepCache#43]
Hello, I would like to ask what is the prompt file for the validation set of the coco dataset used in your assessment, what validation set title did you use, and also how many images did you generate based on each of the prompts.

**Comment by horseee** [comment]
Hi,  you can refer to the code snippet [here](https://github.com/horseee/DeepCache/blob/97813f6406ab71e236bfeb2f8a0e58c6a25b7397/experiments/generate.py#L23):

```
def main(args):
    if args.dataset == 'parti':
        prompts = load_dataset("nateraw/parti-prompts", split="train")
    elif args.dataset == 'coco2017':
        dataset = load_dataset("phiyodr/coco2017")
        prompts = [{"Prompt": sample['captions'][0]} for sample in dataset['validation']]
    else:
        raise NotImplementedError
```

**Comment by ZTzxj** [comment]
Thank you very much.
