### ISSUE TITLE
Use of cache_block_id

### ISSUE THREAD

**Issue by harpavatkeerti** [horseee/DeepCache#8]
Hi, the work looks very interesting.

I was going through the code, and got most part of it, except `cache_block_id`. I didn't get it's usage from the paper, and according to the code, it seems like caching the output of a particular attention block within a UNet layer. 

Could you please provide some insight on this. Thanks!

**Comment by harpavatkeerti** [comment]
Thanks for the clarification @horseee. So, it's a more granular level of control for caching the output of a particular residual path in a layer, if it's the last one, then it's the output of the whole layer, which is detailed in the paper. Else the cache is retrieved from that particular block instead of the previous layer. Is this understanding correct?

**Comment by horseee** [comment]
Hi @harpavatkeerti 

>  it's a more granular level of control for caching the output of a particular residual path in a layer
Correct

> if it's the last one, then it's the output of the whole layer, which is detailed in the paper
If the U-Net has some middle-layer blocks, then the middle-layer blocks would still not be included by choosing the last path.

> Else the cache is retrieved from that particular block instead of the previous layer. 
Correct!
